"""Analysis package exports for Cycle 003 dry-run engines."""

from src.analysis.clustering import cluster_keywords
from src.analysis.competitors import profile_competitors
from src.analysis.contracts import (
    AnalysisError,
    AnalysisEvidence,
    AnalysisPersistenceModel,
    AnalysisReadinessStatus,
    AnalysisResultEnvelope,
    AnalysisRunSummary,
    AnalysisStageSummary,
    AnalysisStatus,
    AnalysisTaskType,
    AnalysisWarning,
    ClusterEntry,
    CompetitorListingInput,
    CompetitorProfileInput,
    CompetitorProfileResult,
    GigQualityInput,
    GigQualityResult,
    IntentInput,
    IntentLabel,
    IntentResult,
    KeywordClusterInput,
    KeywordClusterResult,
    ReviewAnalysisInput,
    ReviewAnalysisResult,
    ReviewSnippetInput,
    SaturationInput,
    SaturationLevel,
    SaturationResult,
    SellerStrengthInput,
    SellerStrengthResult,
)
from src.analysis.gig_quality import score_gig_quality
from src.analysis.intent import classify_intent
from src.analysis.keyword_clusterer import (
    compute_n_clusters,
    load_embeddings_for_niche,
    normalize_embeddings,
    run_clustering_for_all_niches,
    run_clustering_for_niche,
    run_dbscan,
    run_kmeans,
    select_algorithm,
)
from src.analysis.keyword_features import (
    KeywordFeatureError,
    build_keyword_feature_set,
    build_lexical_features,
    extract_tokens,
    normalize_keyword,
    vectorize_keywords,
)
from src.analysis.orchestrator import run_analysis_dry_run
from src.analysis.persistence import persist_analysis_run_summary
from src.analysis.quality import score_gig_quality as score_gig_quality_contract
from src.analysis.registry import build_analysis_output_registry
from src.analysis.reviews import analyze_reviews
from src.analysis.saturation import analyze_saturation
from src.analysis.seller_strength import score_seller_strength
from src.analysis.sellers import score_seller_strength as score_seller_strength_contract

__all__ = [
    "AnalysisError",
    "AnalysisEvidence",
    "AnalysisPersistenceModel",
    "AnalysisReadinessStatus",
    "AnalysisResultEnvelope",
    "AnalysisRunSummary",
    "AnalysisStageSummary",
    "AnalysisStatus",
    "AnalysisTaskType",
    "AnalysisWarning",
    "ClusterEntry",
    "CompetitorListingInput",
    "CompetitorProfileInput",
    "CompetitorProfileResult",
    "GigQualityInput",
    "GigQualityResult",
    "IntentInput",
    "IntentLabel",
    "IntentResult",
    "KeywordClusterInput",
    "KeywordClusterResult",
    "KeywordFeatureError",
    "compute_n_clusters",
    "build_keyword_feature_set",
    "build_lexical_features",
    "classify_intent",
    "cluster_keywords",
    "extract_tokens",
    "load_embeddings_for_niche",
    "normalize_embeddings",
    "normalize_keyword",
    "profile_competitors",
    "run_analysis_dry_run",
    "run_clustering_for_all_niches",
    "run_clustering_for_niche",
    "run_dbscan",
    "run_kmeans",
    "persist_analysis_run_summary",
    "build_analysis_output_registry",
    "SaturationInput",
    "SaturationLevel",
    "SaturationResult",
    "SellerStrengthInput",
    "SellerStrengthResult",
    "score_gig_quality",
    "score_gig_quality_contract",
    "score_seller_strength_contract",
    "score_seller_strength",
    "select_algorithm",
    "analyze_saturation",
    "analyze_reviews",
    "ReviewAnalysisInput",
    "ReviewAnalysisResult",
    "ReviewSnippetInput",
    "vectorize_keywords",
]
