"""Discovery candidate persistence model for E07."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, Float, Index, String, Text, desc
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import Base, IntegerPrimaryKeyMixin, utc_now


class DiscoveryCandidate(IntegerPrimaryKeyMixin, Base):
    """Stores candidate niche hypotheses generated by discovery workflows."""

    __tablename__ = "discovery_candidates"
    __table_args__ = (
        CheckConstraint(
            "hypothesis_type IN ('niche_expansion','adjacent_keyword','trend_signal','reddit_thread','manual_submission')",
            name="ck_discovery_candidates_hypothesis_type",
        ),
        CheckConstraint(
            "status IN ('PENDING','EVALUATED','ACCEPTED','REJECTED','MONITORING')",
            name="ck_discovery_candidates_status",
        ),
        Index(
            "ix_discovery_candidates_status_discovery_score",
            "status",
            desc("discovery_score"),
        ),
        Index(
            "ix_discovery_candidates_source_niche_created_at",
            "source_niche_id",
            "created_at",
        ),
    )

    candidate_id: Mapped[str] = mapped_column(String(128), unique=True, nullable=False)
    hypothesis_text: Mapped[str] = mapped_column(String(1024), nullable=False)
    hypothesis_type: Mapped[str] = mapped_column(String(64), nullable=False)
    source_signal: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    source_niche_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    status: Mapped[str] = mapped_column(String(32), default="PENDING", nullable=False)
    discovery_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    market_size_signal: Mapped[float | None] = mapped_column(Float, nullable=True)
    competition_gap_signal: Mapped[float | None] = mapped_column(Float, nullable=True)
    trend_signal: Mapped[float | None] = mapped_column(Float, nullable=True)
    llm_hypothesis_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
        index=True,
    )
    evaluated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    run_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    user_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
